require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'db/seeds.rb'

Layout/IndentationWidth:
  Width: 2
Layout/LineLength:
  Max: 120
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/Documentation:
  Enabled: false